### ISSUE TITLE
Suddenly Ctrl/Alt+F is interpreted as F by this extension

### ISSUE THREAD

**Issue by ackvf** [samuthekid/fastfind#5]
Perhaps after the latest update from 8.10.19, I cannot use <kbd>Ctrl</kbd><kbd>F</kbd> to bring up chrome's search popup or <kbd>Alt</kbd><kbd>F</kbd> for Menu. When I disable this extension, the shortcuts start working.

In order to bring the popup up, I have to first press <kbd>Alt</kbd> to focus Chrome's Menu Bar.

/Edit after few observations
Pressing <kbd>Ctrl</kbd><kbd>F</kbd> or <kbd>Alt</kbd><kbd>F</kbd> behaves exactly as if I only pressed  <kbd>F</kbd>:
- If I have a text selected, pressing them instead activates this extension's search.
- If I have some selections highlighted, it instead removes latest selection.

**Comment by samuthekid** [comment]
Thanks for your feedback 👍 
As I understand, you are using Windows, and I cannot test because I use macOS :S
I will try to borrow a windows PC to make sure everything works great!

**Comment by ackvf** [comment]
BTW, with the new version, I no longer have this issue.
