### ISSUE TITLE
feature: navigate within highlights

### ISSUE THREAD

**Issue by ackvf** [samuthekid/fastfind#6]
It would be nice to be able to navigate between highlighted words.

- If I have several different highlights and I deselected the highlights, the navigation should go between all
![image](https://user-images.githubusercontent.com/2313018/68076001-b805c200-fdaf-11e9-8008-0f635201bf05.png)
- If I selected some highlight with mouse, then the navigation should be limited only to matches
![image](https://user-images.githubusercontent.com/2313018/68076023-f4392280-fdaf-11e9-8ad0-9d4eaddb6428.png)

For this to work, a deselection should perhaps be implemented as the latest added highlight remains selected until I select or add something else.

I suggest a change to the shortcuts as well
<kbd>F</kbd>
- When text is selected - adds that selection to highlights
- When Highlight is selected - navigates to next matching highlight
- When nothing is selected - navigates to next (any) highlight _(this one is tricky, how to decide which is next?)_

<kbd>Shift</kbd>+<kbd>F</kbd>
- When Highlight is selected - navigates to previous matching highlight
- When nothing is selected - navigates to previous (any) highlight

<kbd>D</kbd>
- When Highlight is selected - removes that highlight
- When nothing is selected - removes all highlights

To prevent accidental removal of all highlights, it can be modified to <kbd>Shift</kbd>+<kbd>D</kbd>

**So how to decide which is next?**
The starting point for "Next" lookup should be the last selected text that was added to highlights.
If that's off the screen, the "Next" should be from the start of current viewport or below. _(I already hate enough how the native Ctrl+F jumps at the top of the page, when I just want to search something where I am currently looking.)_ The user can always return back by Shift+F if that wasn't what they were expecting. If a highlight was deselected, the position of last word should still be known, so the lookup can follow same rules.

**Comment by samuthekid** [comment]
Hello :)
Many thanks for your interest in the FastFind extension!
Before I add more features, I must solve some bugs that I found while using the beta extension.
I will have your opinions and ideas in mind in the next interations of this project!

**Comment by samuthekid** [comment]
Hi! Here are some updates :)

"It would be nice to be able to navigate between highlighted words." - I've now implemented this feature!
I think the state of "having zero elements" selected is something I don't want. It's importante to keep 1 element selected so the user can know for sure what he's doing.

"So how to decide which is next?"
I get a list of all the ffelements from the DOM, ordered by their tree position. From this I just find what is the next or previous ffelement to select ;)

"I suggest a change to the shortcuts as well" - I did this too!
To acomodate the new feature, this is now the shortcuts list:

- F (with selected text) > normal select
- F (without selection) > next element from the same group (old R)
- Shift F > previous element from the same group (old E)

- D > remove current group (old F)
- Shift D > remove all (old D)

- R > next global element (new)
- Shift R > previous global element (new)

- E > next group (old T)
- Shift E > previous group (old W)

**Comment by ackvf** [comment]
WOW, 😍This is amazing!!! Where can I buy you a beer?

The Home page of the extension is kinda broken and there is no Donate Button despite the label.
