### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showSideMap' of null

### ISSUE THREAD

**Issue by ackvf** [samuthekid/fastfind#7]
I cannot log into my online banking.
After I insert my credentials, I get redirected, then I am presented with blank screen and error - if this information helps.
![image](https://user-images.githubusercontent.com/2313018/93187392-0dd12780-f740-11ea-9e4a-649facb94608.png)

**Comment by danielgek** [comment]
@samuthekid im actually having the same symptom ;)

**Comment by danielgek** [comment]
@samuthekid did you release this ?
